export const CLI_EXIT_CODES = {
  SUCCESS: 0,
  UNKNOWN_ERROR: 1,
  INVALID_ARGUMENTS: 2,
  PROVIDER_UNAUTHORIZED: 3,
  PROVIDER_RATE_LIMITED: 4,
  PROVIDER_UNAVAILABLE: 5,
  REQUEST_TIMEOUT: 6,
  INTERRUPTED: 130
} as const

export type CliExitCode = (typeof CLI_EXIT_CODES)[keyof typeof CLI_EXIT_CODES]
